# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='alt',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='lng',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
